package com.example.backend.entity;

import jakarta.persistence.*;

import java.io.Serializable;
import java.util.Objects;

@Entity
@Table(name="questions")
public class Question implements Serializable {
    private Long order;
    @Id
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column questions.text
     *
     * @mbg.generated Sun May 26 01:02:30 CST 2024
     */
    private String text;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column questions.type
     *
     * @mbg.generated Sun May 26 01:02:30 CST 2024
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column questions.survey_id
     *
     * @mbg.generated Sun May 26 01:02:30 CST 2024
     */
    private Long surveyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table questions
     *
     * @mbg.generated Sun May 26 01:02:30 CST 2024
     */
    private static final long serialVersionUID = 1L;


    public Question() {

    }

   public Long getOrder() {
        return order;
    }


    public void setOrder(Long order) {
        this.order = order;
    }
    public Long getId() {
        return id;
    }


    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column questions.text
     *
     * @return the value of questions.text
     *
     * @mbg.generated Sun May 26 01:02:30 CST 2024
     */
    public String getText() {
        return text;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column questions.text
     *
     * @param text the value for questions.text
     *
     * @mbg.generated Sun May 26 01:02:30 CST 2024
     */
    public void setText(String text) {
        this.text = text == null ? null : text.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column questions.type
     *
     * @return the value of questions.type
     *
     * @mbg.generated Sun May 26 01:02:30 CST 2024
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column questions.type
     *
     * @param type the value for questions.type
     *
     * @mbg.generated Sun May 26 01:02:30 CST 2024
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column questions.survey_id
     *
     * @return the value of questions.survey_id
     *
     * @mbg.generated Sun May 26 01:02:30 CST 2024
     */
    public Long getSurveyId() {
        return surveyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column questions.survey_id
     *
     * @param surveyId the value for questions.survey_id
     *
     * @mbg.generated Sun May 26 01:02:30 CST 2024
     */
    public void setSurveyId(Long surveyId) {
        this.surveyId = surveyId;
    }
    public Question(Long id, String text, String type, Long surveyId) {
        this.id = id;
        this.text = text;
        this.type = type;
        this.surveyId = surveyId;
        this.order=null;
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, text, type, surveyId);
    }

    @Override
    public String toString() {
        return "Question{" +
                "id=" + id +
                ", text='" + text + '\'' +
                ", type='" + type + '\'' +
                ", surveyId=" + surveyId + '\''+", order="+ order+
                '}';
    }
}