package com.example.backend.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

import java.io.Serial;
import java.io.Serializable;

@Entity
@Table(name="responses")
public class Response implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column responses.id
     * <p>
     * &#064;mbg.generated  Sun May 26 01:02:30 CST 2024
     */
    @Id
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column responses.question_id
     * <p>
     * &#064;mbg.generated  Sun May 26 01:02:30 CST 2024
     */
    private Long questionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column responses.answer_text
     * <p>
     * &#064;mbg.generated  Sun May 26 01:02:30 CST 2024
     */
    @Column(name = "answer_text",columnDefinition = "LONGVARCHAR",nullable = false)
    private String answerText;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table responses
     * <p>
     * &#064;mbg.generated  Sun May 26 01:02:30 CST 2024
     */
    @Serial
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column responses.id
     *
     * @return the value of responses.id
     *
     * &#064;mbg.generated  Sun May 26 01:02:30 CST 2024
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column responses.id
     *
     * @param id the value for responses.id
     *
     * &#064;mbg.generated  Sun May 26 01:02:30 CST 2024
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column responses.question_id
     *
     * @return the value of responses.question_id
     *
     * &#064;mbg.generated  Sun May 26 01:02:30 CST 2024
     */
    public Long getQuestionId() {
        return questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column responses.question_id
     *
     * @param questionId the value for responses.question_id
     *
     * &#064;mbg.generated  Sun May 26 01:02:30 CST 2024
     */
    public void setQuestionId(Long questionId) {
        this.questionId = questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column responses.answer_text
     *
     * @return the value of responses.answer_text
     *
     * &#064;mbg.generated  Sun May 26 01:02:30 CST 2024
     */
    public String getAnswerText() {
        return this.answerText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column responses.answer_text
     *
     * @param answerText the value for responses.answer_text
     *
     * &#064;mbg.generated  Sun May 26 01:02:30 CST 2024
     */
    public void setAnswerText(String answerText) {
        this.answerText = answerText == null ? null : answerText.trim();
    }
}