package com.example.backend.entity;

import com.example.backend.DTO.SurveyDto;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

import java.io.Serializable;

@Entity
@Table(name="surveys")
public class Survey extends SurveyDto implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column surveys.id
     *
     * @mbg.generated Mon May 27 17:12:41 CST 2024
     */
    @Id
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column surveys.title
     *
     * @mbg.generated Mon May 27 17:12:41 CST 2024
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column surveys.created_by
     *
     * @mbg.generated Mon May 27 17:12:41 CST 2024
     */
    private Integer createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column surveys.description
     *
     * @mbg.generated Mon May 27 17:12:41 CST 2024
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table surveys
     *
     * @mbg.generated Mon May 27 17:12:41 CST 2024
     */
    private static final long serialVersionUID = 1L;

    public Survey(Object o, String employeeEngagement, String yearlyEngagementSurvey) {
    }

    public Survey() {

    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column surveys.id
     *
     * @return the value of surveys.id
     *
     * @mbg.generated Mon May 27 17:12:41 CST 2024
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column surveys.id
     *
     * @param id the value for surveys.id
     *
     * @mbg.generated Mon May 27 17:12:41 CST 2024
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column surveys.title
     *
     * @return the value of surveys.title
     *
     * @mbg.generated Mon May 27 17:12:41 CST 2024
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column surveys.title
     *
     * @param title the value for surveys.title
     *
     * @mbg.generated Mon May 27 17:12:41 CST 2024
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column surveys.created_by
     *
     * @return the value of surveys.created_by
     *
     * @mbg.generated Mon May 27 17:12:41 CST 2024
     */
    public Integer getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column surveys.created_by
     *
     * @param createdBy the value for surveys.created_by
     *
     * @mbg.generated Mon May 27 17:12:41 CST 2024
     */
    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column surveys.description
     *
     * @return the value of surveys.description
     *
     * @mbg.generated Mon May 27 17:12:41 CST 2024
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column surveys.description
     *
     * @param description the value for surveys.description
     *
     * @mbg.generated Mon May 27 17:12:41 CST 2024
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}