package com.example.backend.entity;

import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

import java.io.Serial;
import java.io.Serializable;
@Entity
@Table(name = "surveys_state")
public class SurveyState implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column surveys_state.id
     *
     * @mbg.generated Sat Jun 01 01:42:08 CST 2024
     */
    @Id
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column surveys_state.survey_id
     *
     * @mbg.generated Sat Jun 01 01:42:08 CST 2024
     */
    private Long surveyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column surveys_state.receiveNumber
     *
     * @mbg.generated Sat Jun 01 01:42:08 CST 2024
     */
    private Integer receivenumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column surveys_state.state
     *
     * @mbg.generated Sat Jun 01 01:42:08 CST 2024
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table surveys_state
     *
     * @mbg.generated Sat Jun 01 01:42:08 CST 2024
     */
    @Serial
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column surveys_state.id
     *
     * @return the value of surveys_state.id
     *
     * @mbg.generated Sat Jun 01 01:42:08 CST 2024
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column surveys_state.id
     *
     * @param id the value for surveys_state.id
     *
     * @mbg.generated Sat Jun 01 01:42:08 CST 2024
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column surveys_state.survey_id
     *
     * @return the value of surveys_state.survey_id
     *
     * @mbg.generated Sat Jun 01 01:42:08 CST 2024
     */
    public Long getSurveyId() {
        return surveyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column surveys_state.survey_id
     *
     * @param surveyId the value for surveys_state.survey_id
     *
     * @mbg.generated Sat Jun 01 01:42:08 CST 2024
     */
    public void setSurveyId(Long surveyId) {
        this.surveyId = surveyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column surveys_state.receiveNumber
     *
     * @return the value of surveys_state.receiveNumber
     *
     * @mbg.generated Sat Jun 01 01:42:08 CST 2024
     */
    public Integer getReceivenumber() {
        return receivenumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column surveys_state.receiveNumber
     *
     * @param receivenumber the value for surveys_state.receiveNumber
     *
     * @mbg.generated Sat Jun 01 01:42:08 CST 2024
     */
    public void setReceivenumber(Integer receivenumber) {
        this.receivenumber = receivenumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column surveys_state.state
     *
     * @return the value of surveys_state.state
     *
     * @mbg.generated Sat Jun 01 01:42:08 CST 2024
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column surveys_state.state
     *
     * @param state the value for surveys_state.state
     *
     * @mbg.generated Sat Jun 01 01:42:08 CST 2024
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }
}