package com.example.backend.entity;

import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.io.Serializable;
import java.util.Objects;

@Entity
@Table(name = "users")
public class User implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wjx..user.id
     *
     * @mbg.generated Sun May 26 01:02:30 CST 2024
     */

    @Id
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wjx..user.name
     *
     * @mbg.generated Sun May 26 01:02:30 CST 2024
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wjx..user.age
     *
     * @mbg.generated Sun May 26 01:02:30 CST 2024
     */
    private Short age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wjx..user.gender
     *
     * @mbg.generated Sun May 26 01:02:30 CST 2024
     */
    private Short gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wjx..user.phone
     *
     * @mbg.generated Sun May 26 01:02:30 CST 2024
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wjx..user.password
     *
     * @mbg.generated Sun May 26 01:02:30 CST 2024
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wjx..user.email
     *
     * @mbg.generated Sun May 26 01:02:30 CST 2024
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wjx..user
     *
     * @mbg.generated Sun May 26 01:02:30 CST 2024
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wjx..user.id
     *
     * @return the value of wjx..user.id
     *
     * @mbg.generated Sun May 26 01:02:30 CST 2024
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wjx..user.id
     *
     * @param id the value for wjx..user.id
     *
     * @mbg.generated Sun May 26 01:02:30 CST 2024
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wjx..user.name
     *
     * @return the value of wjx..user.name
     *
     * @mbg.generated Sun May 26 01:02:30 CST 2024
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wjx..user.name
     *
     * @param name the value for wjx..user.name
     *
     * @mbg.generated Sun May 26 01:02:30 CST 2024
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wjx..user.age
     *
     * @return the value of wjx..user.age
     *
     * @mbg.generated Sun May 26 01:02:30 CST 2024
     */
    public Short getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wjx..user.age
     *
     * @param age the value for wjx..user.age
     *
     * @mbg.generated Sun May 26 01:02:30 CST 2024
     */
    public void setAge(Short age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wjx..user.gender
     *
     * @return the value of wjx..user.gender
     *
     * @mbg.generated Sun May 26 01:02:30 CST 2024
     */
    public Short getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wjx..user.gender
     *
     * @param gender the value for wjx..user.gender
     *
     * @mbg.generated Sun May 26 01:02:30 CST 2024
     */
    public void setGender(Short gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wjx..user.phone
     *
     * @return the value of wjx..user.phone
     *
     * @mbg.generated Sun May 26 01:02:30 CST 2024
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wjx..user.phone
     *
     * @param phone the value for wjx..user.phone
     *
     * @mbg.generated Sun May 26 01:02:30 CST 2024
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wjx..user.password
     *
     * @return the value of wjx..user.password
     *
     * @mbg.generated Sun May 26 01:02:30 CST 2024
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wjx..user.password
     *
     * @param password the value for wjx..user.password
     *
     * @mbg.generated Sun May 26 01:02:30 CST 2024
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wjx..user.email
     *
     * @return the value of wjx..user.email
     *
     * @mbg.generated Sun May 26 01:02:30 CST 2024
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wjx..user.email
     *
     * @param email the value for wjx..user.email
     *
     * @mbg.generated Sun May 26 01:02:30 CST 2024
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }
    public User() {}

    public User(Integer id, String name, Short age, Short gender, String phone, String password, String email) {
        this.id = id;
        this.name = name;
        this.age = age;
        this.gender = gender;
        this.phone = phone;
        this.password = password;
        this.email = email;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        User user = (User) o;
        return Objects.equals(id, user.id) && Objects.equals(name, user.name) && Objects.equals(age, user.age) && Objects.equals(gender, user.gender) && Objects.equals(phone, user.phone) && Objects.equals(password, user.password) && Objects.equals(email, user.email);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, name, age, gender, phone, password, email);
    }

    @Override
    public String toString() {
        return "User{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", age=" + age +
                ", gender=" + gender +
                ", phone='" + phone + '\'' +
                ", password='" + password + '\'' +
                ", email='" + email + '\'' +
                '}';
    }
}