package com.example.backend.mapper;

import com.example.backend.entity.Option;
import com.example.backend.entity.OptionExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface OptionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table options
     *
     * @mbg.generated Sun May 26 01:02:30 CST 2024
     */
    long countByExample(OptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table options
     *
     * @mbg.generated Sun May 26 01:02:30 CST 2024
     */
    int deleteByExample(OptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table options
     *
     * @mbg.generated Sun May 26 01:02:30 CST 2024
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table options
     *
     * @mbg.generated Sun May 26 01:02:30 CST 2024
     */
    int insert(Option record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table options
     *
     * @mbg.generated Sun May 26 01:02:30 CST 2024
     */
    int insertSelective(Option record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table options
     *
     * @mbg.generated Sun May 26 01:02:30 CST 2024
     */
    List<Option> selectByExample(OptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table options
     *
     * @mbg.generated Sun May 26 01:02:30 CST 2024
     */
    Option selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table options
     *
     * @mbg.generated Sun May 26 01:02:30 CST 2024
     */
    int updateByExampleSelective(@Param("record") Option record, @Param("example") OptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table options
     *
     * @mbg.generated Sun May 26 01:02:30 CST 2024
     */
    int updateByExample(@Param("record") Option record, @Param("example") OptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table options
     *
     * @mbg.generated Sun May 26 01:02:30 CST 2024
     */
    int updateByPrimaryKeySelective(Option record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table options
     *
     * @mbg.generated Sun May 26 01:02:30 CST 2024
     */



    Option selectByQuestionId(long l);

}