package com.example.backend.mapper;

import com.example.backend.DTO.OptionDto;
import com.example.backend.entity.Question;
import com.example.backend.entity.QuestionExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface QuestionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questions
     *
     * @mbg.generated Sun May 26 01:02:30 CST 2024
     */
    long countByExample(QuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questions
     *
     * @mbg.generated Sun May 26 01:02:30 CST 2024
     */
    int deleteByExample(QuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questions
     *
     * @mbg.generated Sun May 26 01:02:30 CST 2024
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questions
     *
     * @mbg.generated Sun May 26 01:02:30 CST 2024
     */
    int insert(Question record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questions
     *
     * @mbg.generated Sun May 26 01:02:30 CST 2024
     */
    int insertSelective(Question record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questions
     *
     * @mbg.generated Sun May 26 01:02:30 CST 2024
     */
    List<Question> selectByExample(QuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questions
     *
     * @mbg.generated Sun May 26 01:02:30 CST 2024
     */
    Question selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questions
     *
     * @mbg.generated Sun May 26 01:02:30 CST 2024
     */
    int updateByExampleSelective(@Param("record") Question record, @Param("example") QuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questions
     *
     * @mbg.generated Sun May 26 01:02:30 CST 2024
     */
    int updateByExample(@Param("record") Question record, @Param("example") QuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questions
     *
     * @mbg.generated Sun May 26 01:02:30 CST 2024
     */
    int updateByPrimaryKeySelective(Question record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table questions
     *
     * @mbg.generated Sun May 26 01:02:30 CST 2024
     */
    int updateByPrimaryKey(Question record);

    List<OptionDto> getOptionsForQuestion(Long questionId);

    List<Question> selectBySurveyId(Long surveyId);
}