package com.example.backend.mapper;

import com.example.backend.entity.Response;
import com.example.backend.entity.ResponseExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface ResponseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table responses
     *
     * @mbg.generated Sun May 26 01:02:30 CST 2024
     */
    long countByExample(ResponseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table responses
     *
     * @mbg.generated Sun May 26 01:02:30 CST 2024
     */
    int deleteByExample(ResponseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table responses
     *
     * @mbg.generated Sun May 26 01:02:30 CST 2024
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table responses
     *
     * @mbg.generated Sun May 26 01:02:30 CST 2024
     */
    int insert(Response record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table responses
     *
     * @mbg.generated Sun May 26 01:02:30 CST 2024
     */
    int insertSelective(Response record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table responses
     *
     * @mbg.generated Sun May 26 01:02:30 CST 2024
     */
    List<Response> selectByExampleWithBLOBs(ResponseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table responses
     *
     * @mbg.generated Sun May 26 01:02:30 CST 2024
     */
    List<Response> selectByExample(ResponseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table responses
     *
     * @mbg.generated Sun May 26 01:02:30 CST 2024
     */
    Response selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table responses
     *
     * @mbg.generated Sun May 26 01:02:30 CST 2024
     */
    int updateByExampleSelective(@Param("record") Response record, @Param("example") ResponseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table responses
     *
     * @mbg.generated Sun May 26 01:02:30 CST 2024
     */
    int updateByExampleWithBLOBs(@Param("record") Response record, @Param("example") ResponseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table responses
     *
     * @mbg.generated Sun May 26 01:02:30 CST 2024
     */
    int updateByExample(@Param("record") Response record, @Param("example") ResponseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table responses
     *
     * @mbg.generated Sun May 26 01:02:30 CST 2024
     */
    int updateByPrimaryKeySelective(Response record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table responses
     *
     * @mbg.generated Sun May 26 01:02:30 CST 2024
     */
    int updateByPrimaryKeyWithBLOBs(Response record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table responses
     *
     * @mbg.generated Sun May 26 01:02:30 CST 2024
     */
    int updateByPrimaryKey(Response record);
}