package com.example.backend.mapper;

import com.example.backend.entity.SurveyState;
import com.example.backend.entity.SurveyStateExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface SurveyStateMapper {
    SurveyState selectSurveyStateBySurveyId(Long surveyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table surveys_state
     *
     * @mbg.generated Sat Jun 01 01:42:08 CST 2024
     */
    long countByExample(SurveyStateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table surveys_state
     *
     * @mbg.generated Sat Jun 01 01:42:08 CST 2024
     */
    int deleteByExample(SurveyStateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table surveys_state
     *
     * @mbg.generated Sat Jun 01 01:42:08 CST 2024
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table surveys_state
     *
     * @mbg.generated Sat Jun 01 01:42:08 CST 2024
     */
    int insert(SurveyState record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table surveys_state
     *
     * @mbg.generated Sat Jun 01 01:42:08 CST 2024
     */
    int insertSelective(SurveyState record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table surveys_state
     *
     * @mbg.generated Sat Jun 01 01:42:08 CST 2024
     */
    List<SurveyState> selectByExample(SurveyStateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table surveys_state
     *
     * @mbg.generated Sat Jun 01 01:42:08 CST 2024
     */
    SurveyState selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table surveys_state
     *
     * @mbg.generated Sat Jun 01 01:42:08 CST 2024
     */
    int updateByExampleSelective(@Param("record") SurveyState record, @Param("example") SurveyStateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table surveys_state
     *
     * @mbg.generated Sat Jun 01 01:42:08 CST 2024
     */
    int updateByExample(@Param("record") SurveyState record, @Param("example") SurveyStateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table surveys_state
     *
     * @mbg.generated Sat Jun 01 01:42:08 CST 2024
     */
    int updateByPrimaryKeySelective(SurveyState record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table surveys_state
     *
     * @mbg.generated Sat Jun 01 01:42:08 CST 2024
     */
    int updateByPrimaryKey(SurveyState record);
}