package com.example.backend.mapper;

import com.example.backend.entity.User;
import com.example.backend.entity.UserExample;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

import java.util.List;

@Mapper
public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wjx..user
     *
     * @mbg.generated Sun May 26 00:50:17 CST 2024
     */
    long countByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wjx..user
     *
     * @mbg.generated Sun May 26 00:50:17 CST 2024
     */
    int deleteByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wjx..user
     *
     * @mbg.generated Sun May 26 00:50:17 CST 2024
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wjx..user
     *
     * @mbg.generated Sun May 26 00:50:17 CST 2024
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wjx..user
     *
     * @mbg.generated Sun May 26 00:50:17 CST 2024
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wjx..user
     *
     * @mbg.generated Sun May 26 00:50:17 CST 2024
     */
    List<User> selectByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wjx..user
     *
     * @mbg.generated Sun May 26 00:50:17 CST 2024
     */
    User selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wjx..user
     *
     * @mbg.generated Sun May 26 00:50:17 CST 2024
     */
    int updateByExampleSelective(@Param("record") User record, @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wjx..user
     *
     * @mbg.generated Sun May 26 00:50:17 CST 2024
     */
    int updateByExample(@Param("record") User record, @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wjx..user
     *
     * @mbg.generated Sun May 26 00:50:17 CST 2024
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wjx..user
     *
     * @mbg.generated Sun May 26 00:50:17 CST 2024
     */
    int updateByPrimaryKey(User record);

    @Select("select * from users where name = #{name}")
    User findByName(String name);

    @Select("SELECT * FROM users WHERE email = #{email}")
    User findByEmail(String email);

    @Insert("INSERT INTO users (name, age, gender, phone, password, email) VALUES (#{name}, #{age}, #{gender}, #{phone}, #{password}, #{email})")
    int insertUser(User user);
}